// AUTHENTICATION

export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGGED_USER = "AUTH_LOGGED_USER";
export const LOGOUT = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// NOTIFICATIONS

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

// LOADER
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

// RUBROS
export const GET_RUBROS = "GET_RUBROS";

// GASTOS
export const ALTA_GASTOS = "ALTA_GASTOS";
export const GET_GASTOS = "GET_GASTOS";
export const DELETE_GASTOS = "DELETE_GASTOS";
